version: "3.9"

services:

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=haslo1
      - MYSQL_DATABASE=sql-io
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=haslo2
    ports:
      - "3307:3306"